DWAPlannerROS:
  max_vel_x: 0.2
  min_vel_x: 0.0
  max_vel_theta: 1.5
  min_vel_theta: -1.5
  acc_lim_x: 1.0
  acc_lim_theta: 2.0
  sim_time: 1.0
  vx_samples: 10
  vtheta_samples: 20
  xy_goal_tolerance: 0.05
  yaw_goal_tolerance: 0.1
  path_distance_bias: 24.0
  goal_distance_bias: 18.0
  occdist_scale: 0.05
  forward_point_distance: 0.325
